### ISSUE TITLE
Beatmap Combinator not working

### ISSUE THREAD

**Issue by kuwoh** [ppy/osu-stream#15]
Throws this error

> An error occurred during combination:
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Security.Cryptography.SymmetricAlgorithm.set_Key(Byte[] value)
   at osum.Helpers.AesManaged.set_Key(Byte[] value) in D:\osu-stream-master\osu!stream\Helpers\osu!common\AesManaged.cs:line 112
   at osum.Helpers.MapPackage.Save() in D:\osu-stream-master\osu!stream\Helpers\osu!common\MapPackage.cs:line 1201
   at BeatmapCombinator.BeatmapCombinator.writePackage(String oscFilename, String osz2Filename, String audioFilename, List`1 difficulties, List`1 ordered) in D:\osu-stream-master\BeatmapCombinator\Program.cs:line 652
   at BeatmapCombinator.BeatmapCombinator.Process(String dir, Boolean quick, Boolean usem4a, Boolean free, Boolean previewMode) in D:\osu-stream-master\BeatmapCombinator\Program.cs:line 432
   at BeatmapCombinator.BeatmapCombinator.Main(String[] args) in D:\osu-stream-master\BeatmapCombinator\Program.cs:line 49

**Comment by peppy** [comment]
Thanks for opening an issue. The error should make it obvious what's going on. This code base is provided as-is and it should be easy to figure out what's the cause and maybe PR a fix or add documentation.

**Comment by Aikoyori** [comment]
@kuwoh I had the same error and I figured you need `metadata.txt` with all the details listed in Google Docs.
